### ISSUE TITLE
panic occurring on writes when batch is empty.

### ISSUE THREAD

**Issue by mavidser** [Abramovic/logrus_influxdb#21]
Basically, if no logs have been added during some interval and batching has been turned on, a panic occurs when it tries to write the logs.

**Comment by abramovic** [comment]
looks like you fixed it here?  https://github.com/abramovic/logrus_influxdb/pull/22 thanks for the PR!

**Comment by mavidser** [comment]
Yeah. I was under the impression that the issue would have closed upon merging. :)
